apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
        - image: ${DOCKER_USERNAME}/${API_IMAGE}:${VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASS
              value: "${DB_PASS}"
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: LOG_DIR
              value: "/var/logs/crud"
            - name: LOKI_HOST
              value: "${LOKI_HOST}"
      serviceAccountName: ${GCP_SA_EMAIL}
